name: sapphire
channels:
  - conda-forge
  - defaults
dependencies:
  - python == 3.10
  - pip
  - numpy >= 1.23.0
  - scipy >= 1.9.0
  - matplotlib >= 3.5.0
  - astropy >= 5.1
  - h5py
  - yt >= 4.1.2
  - pytables
  - pip: 
    - configparser >= 5.3.0
    - ytree >= 3.2.0
