name: sapphire
channels:
  - conda-forge
dependencies:
  - python == 3.12
  - matplotlib 
  - pandas
  - ytree
  - jax
  - multiprocess
  - numpyro
  - seaborn
  - equinox
  - diffrax
  - optax
  - flax
  - astropy
  - arviz
  - pip
  - pip:
     - interpax
     - chainconsumer
